### ISSUE TITLE
 fetch undefined

### ISSUE THREAD

**Issue by salamichel** [binckbank-api/client-excel#2]
Hi !

I would like to try to use this amazing tool !

* I have imported yaml, correctly, i fill token and everything

But when i click on getPosition or other option, i got 
`["« fetch » est indéfini", "https://script-lab-runner.azureedge.net/?backButton=true", 212, 5, ReferenceError]`

* Library tab seems to be OK

![image](https://user-images.githubusercontent.com/3256040/77641262-0df42580-6f5c-11ea-8128-2bfac2a64cc5.png)

Do you have any idea what is going wrong ?

**Comment by basgroot** [comment]
Hi Stéphane,

If you add this script to the list of libraries, does that solve the reference error?
https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.4/fetch.js

Thanks,
Bas

**Comment by salamichel** [comment]
Yes it's works ! Thx
